title: This is my attempt at a GitHub blog
author: Zoe M
email: zoemesman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I don't have any useful description to provide since this is a test.
  And another change in the description.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
